### PR TITLE
Feat 668 switch graph axis

### PR DESCRIPTION
**Pull request by micahwoodard**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
- switch position of L and R on graph
### What issues or discussions does this update address?
- #668 
### Describe the expected change in behavior from the perspective of the experimenter
- position of L and R are flipped on graph
### Describe any manual update steps for task computers
- None
### Was this update tested in 446/447?
- [ ] 446

### CODE REVIEW

**Comment by micahwoodard** [comment]
image
Here's what it looks like now which is flipped from current implementation on main

**Comment by alexpiet** [comment]
This switches the labels, but not the plot itself

**Comment by micahwoodard** [comment]
Ahh okay my bad I thought it was just switching axis labels. I'll work more

**Comment by hagikent** [comment]
@micahwoodard 
Yes, the content to be visualized has to be flipped, not only labels.
Note, the data to be saved for analysis should be kept as is! Down-stream analysis convention shouldn't be changed.

**Comment by alexpiet** [comment]
@micahwoodard You might be able to do something as simple as `plt.gca().invert_yaxis()`

**Comment by micahwoodard** [comment]
@alexpiet  and @hagikent I think it should be fixed now. Per Alex's suggestion, I just flipped the y axis orientation instead. Here is what it looks like now. 
image

**Review by alexpiet — APPROVED** [review]

**Pull request merged**
