### PR TITLE
Show video 2

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
Updated the bonsai layout file to automatically open the video visualization when bonsai is started.

### What issues or discussions does this update address?
https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/351#event-12543503251

### Describe the expected change in behavior from the perspective of the experimenter
For behavior rigs, we can close these video windows manually if we don't use it.
For ephys rigs, video visualization windows for bottom and right cameras will be open automatically.

### Describe any manual update steps for task computers
No

### Was this update tested in 446/447?
Tested on my own computer.

### CODE REVIEW

**Comment by XX-Yin** [comment]
@alexpiet @hanhou 
The original PR (https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/459) had difficult to resolve conflicts in the bonsai files, so I created a new PR.

**Comment by XX-Yin** [comment]
@alexpiet 
I don't know how to label the `VideoWriter` window. Do you have any ideas?

**Comment by alexpiet** [comment]
> @alexpiet I don't know how to label the `VideoWriter` window. Do you have any ideas?

No. I'll ask bruno. We can move ahead with the rest of this PR

**Comment by XX-Yin** [comment]
> > @alexpiet I don't know how to label the `VideoWriter` window. Do you have any ideas?
> 
> No. I'll ask bruno. We can move ahead with the rest of this PR

I have changed the layout file to open the video window by default.

**Comment by alexpiet** [comment]
Bruno says it requires updating bonsai. I made a separate issue: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/530

**Comment by XX-Yin** [comment]
> Bruno says it requires updating bonsai. I made a separate issue: #530

Ok, let's update the bonsai first.

**Review by alexpiet — APPROVED** [review]

**Comment by XX-Yin** [comment]
I will merge this. We can label the window of video writer after updating the bonsai.

**Pull request merged**
