### PR TITLE
Fix uncoupled block

### PR DESCRIPTION
**Pull request by hanhou**
### Describe changes:
- Use the same uncoupled task logic as in Grossman 2022 and Su 2022 (Python implementation of the Arduino code)
- Use `anti_perseverative` to fight against bias in uncoupled tasks
    - However, I hardcode perserverative_limit = 4 and max_block_tally = 3 for now
- Accordingly, the following block controls are disabled because they don't make much sense when blocks are uncoupled:
  - The manual "NextBlock" button (maybe we'll add "NextLeftBlock" and "NextRightBlock" in the future)
  - Block hold based on `BlockMinReward`
  - Block hold based on `AdvancedBlock` (recent choice proportion)

### What issues or discussions does this update address?
- Replaces #204 
- Finally resolves https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/36
- Resolves https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/169#issuecomment-1911041687
- Resolves https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/239
- Resolves https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/261

### Describe the expected change in behavior from the perspective of the experimenter
- The uncoupled blocks should be more balanced.
- The anti-perseverative is harded coded and turned on by default, like in Grossman and Su's papers.

### Describe the outcome of testing this update on a rig in 447
- [x] tested on my PC
    - [x] Uncoupled task matches the one described in Grossman et al 
    - [x] Uncoupled task responds correctly to a biased agent
    - [x] Has no interference with Coupled / Reward N task, and the user can switch among them smoothly
    - [x] Works well with warmup and autotrain

### CODE REVIEW

**Comment by hanhou** [comment]
- [] Get the parameters and initialize the class
- [] set `self.RewardProbPoolUncoupled`
- [] set `self.B_CurrentRewardProb`
- [] set `self.BlockLen`
- [] set `self.BlockLenHistory`
- [] handle `self.B_ANewBlock`

**Comment by hanhou** [comment]
@XX-Yin while I'm refactoring the code before plugging in my class, please start to review my changes to make sure I understand your logic correctly.

**Review by XX-Yin — COMMENTED** [review]
@hanhou It looks good. I don't see issues.

**Comment by hanhou** [comment]
@XX-Yin  can you help me understand this function https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/f908229125ff4fd1818b21baf3613978201556af/src/foraging_gui/MyFunctions.py#L412-L428

Why do you need this since you alrady have https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/f908229125ff4fd1818b21baf3613978201556af/src/foraging_gui/MyFunctions.py#L313 and https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/f908229125ff4fd1818b21baf3613978201556af/src/foraging_gui/MyFunctions.py#L349

Do you use it to recalculate the actual block length history after any type of block manipulation, such as holding the block to fight against bias?

**Comment by XX-Yin** [comment]
> @XX-Yin can you help me understand this function
> 
> https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/f908229125ff4fd1818b21baf3613978201556af/src/foraging_gui/MyFunctions.py#L412-L428
> 
> Why do you need this since you already have
> 
> https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/f908229125ff4fd1818b21baf3613978201556af/src/foraging_gui/MyFunctions.py#L313
> 
> and
> https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/f908229125ff4fd1818b21baf3613978201556af/src/foraging_gui/MyFunctions.py#L349
> 
> Do you use it to recalculate the actual block length history after any type of block manipulation, such as holding the block to fight against bias?

@hanhou You are right. `self.BlockLenHistory[i].append(self.BlockLen)` is the expected block length. It could be changed by holding the block or pressing the `NextBlock` button. It's safer to compute the actual block length.

**Comment by hanhou** [comment]
My code transplant now seems to work, although I'll do more tests. @XX-Yin @ZhixiaoSu 

- green: both sides is the lowest, push the previously lowest one to a higher prob
- red: one side is higher for 3 consecutive blocks, push it to the lowest
image

**Comment by hanhou** [comment]
> @hanhou You are right. `self.BlockLenHistory[i].append(self.BlockLen)` is the expected block length. It could be changed by holding the block or pressing the `NextBlock` button. It's safer to compute the actual block length.

Thanks. I have renamed it to `_override_block_len`. In general, it would be great to add more comments and/or use more explicit name for such code that is not quite self-explanatory.

**Comment by hanhou** [comment]
Tested a left-biased agent and the GUI correctly extended the right block until the agent's bias was reduced.

image

**Comment by hanhou** [comment]
- [ ] Fix the bug where the user switch coupled/uncoupled in the middle of a session.

**Comment by hanhou** [comment]
@XX-Yin @ZhixiaoSu this PR is ready for review.

**Comment by hanhou** [comment]
@XX-Yin @ZhixiaoSu @alexpiet It would be great if this PR can be reviewed and merged this week.

**Comment by alexpiet** [comment]
> @XX-Yin @ZhixiaoSu @alexpiet It would be great if this PR can be reviewed and merged this week.

I dont have any bandwidth to review this right now.

**Comment by XX-Yin** [comment]
> @XX-Yin @ZhixiaoSu @alexpiet It would be great if this PR can be reviewed and merged this week.

I don't have bandwidth either. There are a lot of changes. Do you test different tasks (simulation state should be ok)? Coupled, uncoupled and RewardN.

**Comment by ZhixiaoSu** [comment]
Sorry, I don't think I have enough knowledge of the code to review it. But if the modification is only about the uncoupled task and it is relatively local, I can try to review and approve it. As long as it won't affect other versions of the task, I can take the responsibility if there are bugs that affect uncoupled task only (I believe it should be rare case.).

**Review by ZhixiaoSu — APPROVED** [review]

**Comment by hanhou** [comment]
> > @XX-Yin @ZhixiaoSu @alexpiet It would be great if this PR can be reviewed and merged this week.
> 
> I don't have bandwidth either. There are a lot of changes. Do you test different tasks (simulation state should be ok)? Coupled, uncoupled and RewardN.

Yes. I added the tests I've done in the PR description
image

**Comment by hanhou** [comment]
> Sorry, I don't think I have enough knowledge of the code to review it. But if the modification is only about the uncoupled task and it is relatively local, I can try to review and approve it. As long as it won't affect other versions of the task, I can take the potential risk in uncouple unbaited task if there are bugs that affect uncoupled task only (I believe it should be rare case.).

Thanks Sue! Let's keep an eye on the first batch of mice using the new Uncoupled task. btw, congrats on the visa -- that's so fast!

**Comment by ZhixiaoSu** [comment]
Great! I'll ask Jackie to test it on the current few animals. (And yes, I just got an email saying my passport is ready for pick-up tomorrow! Highly recommend Vancouver for visa interviews.)

**Comment by hanhou** [comment]
First real mouse running on the new Uncoupled task. The block structure seems good. 
2024-02-26, 710414, Session 9
image

**Pull request merged**
