### PR TITLE
Updating names of boxes and towers

### PR DESCRIPTION
**Pull request by alexpiet**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "production_testing" into "main" should use the keyword "production merge" in the title for reliable indexing of updates
  
### Describe changes:
- Our change in naming convention prompts updates to how we refer to boxes, and towers. I'm using this as an opportunity to fix some confusing terms in the code. I also realized that #145 is flawed in that the boxes will still be referred to as A-D in the tower, so I am effectively reversing that PR. 
- The code is still a little confusing because of two issues:
    - First, internally, and when loading settings and calibration files it uses the nomenclature of box1,2,3,4, not A,B,C,D. But I don't think this is worth fixing because when we move to one box/computer, we wont need all this logic anyways (https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/157)
    - Second, https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/156

### What issues or discussions does this update address?
- #147 
- Reverses #145 
- Fixes changes prompted by https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/158

### Describe the expected change in behavior from the perspective of the experimenter
- no changes

### Describe the outcome of testing this update on a rig in 447
- [x] tested in 447

### CODE REVIEW

**Comment by alexpiet** [comment]
@hanhou @XX-Yin Can you review this PR?

**Review by XX-Yin — COMMENTED** [review]
You rename box like 447-1-A. Do you add these boxes name to the GUI object Tower? If not, the GUI can't select 447-1-A.

**Comment by alexpiet** [comment]
> You rename box like 447-1-A. Do you add these boxes name to the GUI object Tower? If not, the GUI can't select 447-1-A.

No, I didn't. My plan was to remove the GUI object Tower altogether (see https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/158)

**Comment by XX-Yin** [comment]
> > You rename box like 447-1-A. Do you add these boxes name to the GUI object Tower? If not, the GUI can't select 447-1-A.
> 
> No, I didn't. My plan was to remove the GUI object Tower altogether (see #158)

That sounds good! I will approve this.  

We should add the new rig name to the GUI like shown below if we make changes.
image

**Review by XX-Yin — APPROVED** [review]

**Pull request merged**
