### PR TITLE
Update trial logic

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
Updated the trial logic for optogenetics session. 

Previously, the optogenetics session is using a trial logic without the delay period (due to precise control of duration during the ITI period) for both opto and control trials. 
image

After updating, the opto trials and control trials will use the opto and normal trial logic, respectively. 
image

### What issues or discussions does this update address?
See description on the "Describe changes"

### Describe the expected change in behavior from the perspective of the experimenter
No

### Describe any manual update steps for task computers
No

### Was this update tested in 446/447?
Tested on 323_Ephys3

### CODE REVIEW

**Comment by XX-Yin** [comment]
@alexpiet @micahwoodard This is ready for review.

**Comment by XX-Yin** [comment]
@micahwoodard @alexpiet Can you review this PR this week so that we can merge it EOD Friday?

**Comment by alexpiet** [comment]
Does this change anything about non-opto sessions?

@hanhou any input?

**Comment by micahwoodard** [comment]
I do not know enough bonsai to provide any meaningful review on this, but I'll look through and see if anything makes sense to me!

**Comment by XX-Yin** [comment]
> Does this change anything about non-opto sessions?
> 
> @hanhou any input?

No, nothing was changed for the non-opto session.

**Comment by hanhou** [comment]
I don't have enough bonsai knowledge to review the workflow change either. But in general, could you explain why maintaining two trial structures is necessary? What is the delay period you mentioned? Could you discuss with Bruno to see whether the change is necessary and optimized?

**Comment by XX-Yin** [comment]
> I don't have enough bonsai knowledge to review the workflow change either. But in general, could you explain why maintaining two trial structures is necessary? What is the delay period you mentioned? Could you discuss with Bruno to see whether there are better solutions?
> 
> And maybe I misunderstood, but the first diagram you posted seems to be the updated one, as there are two separate workflows?

Yes, there are two trial logic. For the opto, we don't have the delay period in order to give precise duration of laser. For normal trials, the logic is as before (no change in the code), and we have a delay period. 

I have implemented the same logic in the previous version. However, they are separated and can't be used in the same session. Here, the update is to permit using two logic in the same session. 

I have already talked with Bruno long time ago.

**Comment by XX-Yin** [comment]
I don't change the trial logic here, instead I combine two trial logic to a single chain. Previously, only one trial logic can be used (either normal or the opto) in a single session (due to termination of the other chain after first trial). After combining two trial logic to a single chain, two trial logic can be interleaved in a single session.

**Comment by XX-Yin** [comment]
> I don't change the trial logic here, instead I combine two trial logic to a single chain. Previously, only one trial logic can be used (either normal or the opto) in a single session (due to termination of the other chain after first trial). After combining two trial logic to a single chain, two trial logic can be interleaved in a single session.

**Comment by alexpiet** [comment]
I'm nervous because I also don't understand the bonsai workflow to give a meaningful review. Its problematic that we don't have anyone else to review this

**Comment by XX-Yin** [comment]
> I'm nervous because I also don't understand the bonsai workflow to give a meaningful review. Its problematic that we don't have anyone else to review this

I got your concern. This is definitely something we should improve. In terms of this PR, it doesn't change the trial logic. We may consider merging it.

**Review by alexpiet — APPROVED** [review]

**Pull request merged**
