### PR TITLE
Add buttons to the GUI for the Streamlit app

### LINKED ISSUE #201: Add links to the streamlit app
Add links to the streamlit app so that one can check the training history of a mouse easily.

### PR DESCRIPTION
**Pull request by hanhou**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "production_testing" into "main" should use the keyword "production merge" in the title for reliable indexing of updates
  
### Describe changes:
Added three buttons in the GUI that open the Streamlit app for specific mouse and curriculum. The users can then interact with the app. This is made possible by this [PR](https://github.com/AllenNeuralDynamics/foraging-behavior-browser/pull/25) in my Streamlit app.

### What issues or discussions does this update address?
- resolves #201 

### Describe the expected change in behavior from the perspective of the experimenter
1.  The "Streamlit!" button in the main GUI opens the main page of the Streamlit app with `subject_id` filtered.
Behavior rig:
image
Ephys rig:
image
image

2. Two buttons in the AutoTrain GUI open the autotrain history and selected curriculum, respectively.

image
image
image

### Describe the outcome of testing this update on a rig in 447
Tested on my PC and should behave the same in 447.

### CODE REVIEW

**Review by alexpiet — CHANGES_REQUESTED** [review]
You only updated one of the two `.ui` files

**Comment by hanhou** [comment]
oops 😂. Will fix soon.

> You only updated one of the two `.ui` files

**Comment by hanhou** [comment]
Just added to the ephys rig. However, I have to pull @XX-Yin's `local_dev3` to my branch, ending up with a long list of commits...

**Comment by XX-Yin** [comment]
> I realize that this may not be a good idea, since `local_dev3` has some changes that are still WIP (the warmup part). Merging this PR will merging those premature changes as well. @XX-Yin @alexpiet any suggestions?

It seems that we are currently stuck in the local_dev3. I also have some updates dependent on local_dev3. Maybe we should merge local_dev3 to the production_testing, then I address Han's comments?

**Comment by hanhou** [comment]
> > I realize that this may not be a good idea, since `local_dev3` has some changes that are still WIP (the warmup part). Merging this PR will merging those premature changes as well. @XX-Yin @alexpiet any suggestions?
> 
> It seems that we are currently stuck in the local_dev3. I also have some updates dependent on local_dev3. Maybe we should merge local_dev3 to the production_testing, then I address Han's comments?

This sounds doable. As long as the warmup is not turned on, it should not create any trouble. So in the future, let's try to make a PR do only one thing at a time.

**Comment by XX-Yin** [comment]
> > > I realize that this may not be a good idea, since `local_dev3` has some changes that are still WIP (the warmup part). Merging this PR will merging those premature changes as well. @XX-Yin @alexpiet any suggestions?
> > 
> > 
> > It seems that we are currently stuck in the local_dev3. I also have some updates dependent on local_dev3. Maybe we should merge local_dev3 to the production_testing, then I address Han's comments?
> 
> This sounds doable. As long as the warmup is not turned on, it should not create any trouble. So in the future, let's try to make a PR do only one thing at a time.

Right, we should make PR simple and independent in the future.

**Review by alexpiet — APPROVED** [review]

**Pull request merged**
