### PR TITLE
Control open ephys from the GUI

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
1. Starting/Stopping the Open Ephys GUI from the behavior GUI. Adding `Start ephys recording` button and `recording type` combo box (types including behavior, surface finding, opto tagging, testing and NA). 
image
image

2. Sending folder structure to the Open Ephys, and saving the folder structure to the behavior json. 

The logic is:
- When the `Start ephys recording` button is checked:
  - If the ip address is not provided.
image
  - If the behavior has started,
  image
  - If the open ephys software is not open or the ip address is not correct, a warning will pop up
image
  - If the ephys recording has started, a warning will pop up
image
  - If the ephys recording starts normally, a warning will also pop up
image

- When the `Start ephys recording` button is unchecked:
  - If the open ephys recording has stopped, a warning will pop up
image
   - If the behavior has not stopped yet
   image

   - If the open ephys recording stops normally. a warning will pop up to ask user save open ephys related data again.
image

### What issues or discussions does this update address?
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/401

### Describe the expected change in behavior from the perspective of the experimenter
1. We can use the behavioral GUI to control the Open Ephys GUI, the folder structure and some experiment information from open ephys (such as record and experiment numbers) will be saved in the behavioral json.
image

3. Make sure to set the `open_ephys_machine_ip_address` in the  `ForagingSettings.json` to use this function. 

### Describe the outcome of testing this update on a rig in 447
Tested in 323_EPHYS3

### CODE REVIEW

**Review by alexpiet — COMMENTED** [review]
- @XX-Yin I dont understand the software stack for ephys recordings, but I worry this is adding unnecessary complications to link the ephys software and the behavior software. I'll defer to you, since you will be using it. 
- What other ephys users might want to give us feedback on this change? @KanghoonJ @ZhixiaoSu

**Comment by alexpiet** [comment]
Can you provide a screenshot of the primary `ui`?

**Comment by XX-Yin** [comment]
@alexpiet The ephys rig one is using a python script to control the Open Ephys software. Here the main advantage is 1) we could automatically link the behavior session with an ephys recording, which is important for automatically uploading data later. 2) we could unify the software control.

**Comment by alexpiet** [comment]
It looks like the "recording type" has a default value of `40`, and selecting any of the dropdown items does not change this value. What is 40? and why does the drop down menu not work?

**Comment by XX-Yin** [comment]
> dropdown

Hi Alex, I am working on this part. It should be ready for review soon.  I remember I wasn't asking for your review now. Sorry for causing this confusion. I'll let you know when it's done.

**Comment by XX-Yin** [comment]
@alexpiet this is ready for review. 

@KanghoonJ @ZhixiaoSu this is ready for review.

**Comment by alexpiet** [comment]
> > Can you provide a screenshot of the primary `ui`?
> 
> The original ui did not have `Start ephys recording` and `recording type`.
> 

No, I mean a screenshot of the updated `ForagingGUI.ui`

**Comment by KanghoonJ** [comment]
I will review this and let you know. The new feature seems useful!

**Comment by XX-Yin** [comment]
> I will review this and let you know. The new feature seems useful!

@KanghoonJ I'm happy to provide you with a demo in 323_EPHYS1 for feedback.

**Comment by alexpiet** [comment]
@XX-Yin I'm ready to approve once we get feedback from @KanghoonJ and @ZhixiaoSu

**Comment by XX-Yin** [comment]
Based on feedbacks from @KanghoonJ,  I updated the code to check if behavior has stopped when we start (stop) ephys recording. The ephys recording should include the entire behavior session. 

@alexpiet I think this is ready for approving.

**Review by alexpiet — APPROVED** [review]

**Pull request merged**
