### PR TITLE
Start FIP workflow from GUI

### LINKED ISSUE #285: Start FIP workflow from the GUI
- pass the mouse ID as a property string
- start the workflow without the editor
- reduces steps for the RAs
- reduces the chances of a mistake when entering mouse id
- https://bonsai-rx.org/docs/articles/cli.html
- [ ] Why are there multiple bonsai workflows? one for each rig? They should be the same
- [ ] What is the name of the property with the mouse id?
- [ ] FIP data should get saved in the `fib` subfolder. Which means we need to pass the FIP workflow the string for the name of the folder

### LINKED ISSUE #419: FIP updates
- GUI should pass the photometry subfolder for the session, and behavior video subfolder for the session (just pass the root folder)
- GUI needs to pass whether FIP workflow should record video or not
- Add a button to the GUI that starts FIP workflow, which transmits the folder location.

### PR DESCRIPTION
**Pull request by alexpiet**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
- Allows the user to start the FIP workflow from the GUI, and removes the need to manually enter the mouse ID into the FIP workflow. 
- Adds a new entry into `ForagingSettings.json`,  `FIP_workflow_path` with default value of `""`.  This entry is not required unless FIP is running from the GUI. 
- Passes the session path, and whether the camera is running to the FIP workflow

### What issues or discussions does this update address?
- resolves #419 
- resolves #285 

### Describe the expected change in behavior from the perspective of the experimenter

Adds a `Start FIP workflow` button to the Optogenetics and fiber photometry tab. Reorganizes the `Start Excitation` and `Start bleaching` buttons

MicrosoftTeams-imagedf302bb83b1c0bfb2c0ffebe972ae414704ffa98c7f1978db3544cf6ad1704b9

To start the FIP workflow:
- Open the GUI and load the mouse
- Click "Start FIP workflow"
- Once the workflow has opened, click "Start excitation", you will be asked to confirm the FIP workflow is running
- Click "Start" to start the session, and the baseline timer will begin. 

To end the session:
- Click "Start" to stop trials
- Click "Start Excitation" to stop excitation
- click "Stop" in the workflow window
- Save the GUI, close the GUI

### Describe any manual update steps for task computers
FIP rigs must:
- update to the newest version of `FIP_DAQ_Control` repo
- Add `FIP_workflow_path` to `ForagingSettings.json`. This should be a string path to the `ThorFIP.bonsai` workflow in the FIP_DAQ_Control repo
- [x] Ephys 1/3
- [ ] 447 1D, 2D, 3D @hagikent @alexpiet 
- [ ] 428 @hagikent @alexpiet 
- [ ] 446 ? @hagikent 

### Was this update tested in 446/447?
- [ ] tested in 447
- [x] tested in 428

### CODE REVIEW

**Review by hagikent — APPROVED** [review]
Tested on the pilot rig in 428 and it works as designed. To be tested in 447.

**Comment by alexpiet** [comment]
@XX-Yin @hanhou This PR is ready to review, wanted to give you a chance to look at it, even though Kenta approved already

**Review by XX-Yin — CHANGES_REQUESTED** [review]
I am still reviewing the code.

**Comment by XX-Yin** [comment]
Can you add the `fiber_photometry_start_time` and `fiber_photometry_end_time` and save them? They will be used to generate the session metadata.

**Comment by alexpiet** [comment]
> Can you add the `fiber_photometry_start_time` and `fiber_photometry_end_time` and save them? They will be used to generate the session metadata.

@XX-Yin I've added the start/end times

**Review by XX-Yin — APPROVED** [review]

**Comment by XX-Yin** [comment]
It looks good to me.

**Pull request merged**
