### PR TITLE
bias calculation threading fix

### LINKED ISSUE #717: trial stalled 5 minutes, user stopped trials. ANewTrial:1,Start:False,finish_Timer:1
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: _StartTrialLoop<br>line 4105<br>logfile: W10DT714086/W10DT714086-C_gui_log_2024-09-26_08-51-48.txt<br>boxes: 1A, 1C, 2A, 2B, 3D, ephys1, ephys3<br>count: 8<br>text: trial stalled 5 minutes, user stopped trials. ANewTrial:1,Start:False,finish_Timer:1<br><br><br>Log context<br>

```
  RewardedHistoryF[i+1-kernel_size]=np.nanmean(RewardedHistoryT[i+1-kernel_size:i+1])

10:26:52 AM:INFO:Foraging:Foraging.py:_Save:line 2330:Saving current session, ForceSave=1
10:26:52 AM:INFO:Foraging:Foraging.py:_GetWaterCalibration:line 1009:Loaded Water Calibration
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 91:processing:C:\behavior_data\447-1-C\750108\behavior_750108_2024-09-26_09-11-57
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:_handle_edge_cases:line 399:Cannot log reward delivery in session metadata - missing fields
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:_get_reward_delivery:line 1234:No reward delivery metadata found!
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:_get_ephys_stream:line 906:No ephys data stream detected!
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:_get_ophys_stream:line 625:No photometry data stream detected!
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:_get_high_speed_camera_stream:line 603:No camera data stream detected!
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 118:Session metadata generated successfully: True
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 119:Rig metadata generated successfully: True
10:26:52 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 120:Data description generated successfully: True
10:27:01 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/DelayStartTime', 22443830.912, '127.0.0.1', 4022]
10:27:01 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 22443830.913504, '127.0.0.1', 4022]
10:27:02 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/GoCueTime', 22443831.412, '127.0.0.1', 4022]
10:27:02 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 22443831.413504, '127.0.0.1', 4022]
10:27:02 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/GoCueTimeSoundCard', 22443831.414208, 4, '127.0.0.1']
10:27:02 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/AutoLeftWaterStartTime', 22443831.413984, '127.0.0.1', 4023]
10:27:02 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftRewardDeliveryTimeHarp', 22443831.415488, '127.0.0.1', 4023]
10:27:02 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 22443831.943712, '127.0.0.1', 4023]
10:27:02 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RewardOutcomeTime', 22443831.942976, '127.0.0.1', 4022]
10:27:02 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RewardOutcome', 'ErrorRight', '127.0.0.1', 4022]
10:27:03 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/TrialEndTime', 22443832.928992, '127.0.0.1', 4022]
10:27:03 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 22443832.930496, '127.0.0.1', 4022]
10:27:03 AM:INFO:uncoupled_block:uncoupled_block.py:auto_shape_perseverance:line 137:persev at side = R, added 4 trials to both sides
10:27:42 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 22443872.16672, '127.0.0.1', 4023]
10:27:42 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 22443872.317696, '127.0.0.1', 4023]
10:27:43 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 22443872.45472, '127.0.0.1', 4023]
10:32:32 AM:ERROR:Foraging:Foraging.py:_StartTrialLoop:line 4105:trial stalled 5 minutes, user stopped trials. ANewTrial:1,Start:False,finish_Timer:1
```

### PR DESCRIPTION
**Pull request by micahwoodard**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
- only start bias calculation thread if previous calculation is done
### What issues or discussions does this update address?
- resolves #717 
### Describe the expected change in behavior from the perspective of the experimenter
- None
### Describe any manual update steps for task computers
- None
### Was this update tested in 446/447?
- [x] 446/7

### CODE REVIEW

**Comment by micahwoodard** [comment]
@XX-Yin would something like this work for making sure there aren't multiple threads running for bias calculation?

**Comment by XX-Yin** [comment]
> @XX-Yin would something like this work for making sure there aren't multiple threads running for bias calculation?

@micahwoodard This looks good.
I'm not familiar with `self.bias_thread.is_alive()`, I am using a `_thread_complete#` function to indicate the finish of the thread. Either way should work, but please test it in one of the rigs.

**Comment by micahwoodard** [comment]
@XX-Yin can you approve so I can merge?

**Comment by micahwoodard** [comment]
yes

**Review by XX-Yin — APPROVED** [review]

**Pull request merged**
