### PR TITLE
changing kernel size to 10

### LINKED ISSUE #877: visualization bug
@micahwoodard @alexpiet 
The RunLength was set to a fixed value, which caused the update of the figure is not smooth. This variable is set and changed in the GUI. 

Left is the current code, and the right is my previous code. Please make it set by GUI instead of hardcoded!

image
image
image

### PR DESCRIPTION
**Pull request by micahwoodard**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
- change kernel size to 10
### What issues or discussions does this update address?
- resolves #877 
### Describe the expected change in behavior from the perspective of the experimenter
- graph better sized
### Describe any manual update steps for task computers
- None
### Was this update tested in 446/447?
- [ ] 446/7

### CODE REVIEW

**Comment by XX-Yin** [comment]
Hi @micahwoodard 

Can you set the kernel_size by the RunLength from the GUI?

self.RunLength=win.RunLength.text



        # running average of choice
        if self.RunLength()!='':
            kernel_size = int(self.RunLength())
            if kernel_size==1:
                kernel_size=2
                self.RunLengthSetValue(2)
        else:
            kernel_size=2
            self.RunLengthSetValue(2)
        self.kernel_size=kernel_size

**Comment by micahwoodard** [comment]
The issue with that is that those widgets were removed in a previous [pull ](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/445). We either need to add the plot settings back in or hard code this value to 10

**Comment by XX-Yin** [comment]
This parameter is important. This widget is not removed from the ephys GUI. You can directly copy it to the behavior GUI. 
image

**Comment by micahwoodard** [comment]
What does this parameter do? Plot settings were removed from the other gui because they weren't being changed or used by users. I am reluctant to add them back in because of their disuse

**Comment by micahwoodard** [comment]
Also what values does self.RunLength() get set to in your use cases?

**Comment by XX-Yin** [comment]
> What does this parameter do? Plot settings were removed from the other gui because they weren't being changed or used by users. I am reluctant to add them back in because of their disuse

This parameter controls the smoothness of the choice plot, which is important to check it online in some experiments (e.g. in optogenetics, we'd like to see the choice in higher resolution, so the RunLength is set to a smaller value than normal).

**Comment by alexpiet** [comment]
> > What does this parameter do? Plot settings were removed from the other gui because they weren't being changed or used by users. I am reluctant to add them back in because of their disuse
> 
> This parameter controls the smoothness of the choice plot, which is important to check it online in some experiments (e.g. in optogenetics, we'd like to see the choice in higher resolution, so the RunLength is set to a smaller value than normal).

Why do you want the ability to check this in the GUI? For analysis, I understand why you want to look at different resolution, but do you use this for online QA?

**Comment by XX-Yin** [comment]
> > > What does this parameter do? Plot settings were removed from the other gui because they weren't being changed or used by users. I am reluctant to add them back in because of their disuse
> > 
> > 
> > This parameter controls the smoothness of the choice plot, which is important to check it online in some experiments (e.g. in optogenetics, we'd like to see the choice in higher resolution, so the RunLength is set to a smaller value than normal).
> 
> Why do you want the ability to check this in the GUI? For analysis, I understand why you want to look at different resolution, but do you use this for online QA?

Yes, I use it online for visualizing the optogenetics perturbation.

**Comment by alexpiet** [comment]
> > > > What does this parameter do? Plot settings were removed from the other gui because they weren't being changed or used by users. I am reluctant to add them back in because of their disuse
> > > 
> > > 
> > > This parameter controls the smoothness of the choice plot, which is important to check it online in some experiments (e.g. in optogenetics, we'd like to see the choice in higher resolution, so the RunLength is set to a smaller value than normal).
> > 
> > 
> > Why do you want the ability to check this in the GUI? For analysis, I understand why you want to look at different resolution, but do you use this for online QA?
> 
> Yes, I use it online for visualizing the optogenetics perturbation.

But is this just for viewing the data? Or do you modify the way the experiment is going as a result of this perturbation?

**Comment by XX-Yin** [comment]
It's mainly for online monitoring.

**Comment by alexpiet** [comment]
I think we need to move away from treating the GUI as a tool for visualizing the behavior, since its goal is to collect data. Trying to make the GUI too much is part of why its such a messy code base. 

But I know you might disagree. So lets merge this update in, to set the kernel size back to 10, and we can discuss later about what features we want the GUI to support.

**Review by alexpiet — APPROVED** [review]

**Comment by XX-Yin** [comment]
> I think we need to move away from treating the GUI as a tool for visualizing the behavior, since its goal is to collect data. Trying to make the GUI too much is part of why its such a messy code base.
> 
> But I know you might disagree. So lets merge this update in, to set the kernel size back to 10, and we can discuss later about what features we want the GUI to support.

How does this affect the code after adding this functionality?

**Comment by XX-Yin** [comment]
@alexpiet What's exactly your concern? It's just an extra parameter.

**Comment by alexpiet** [comment]
> @alexpiet What's exactly your concern? It's just an extra parameter.

Its not just this one parameter. Its the multiplicative effect of extra parameters, code blocks, and functions. If we want to update something we have to check more cases and conditions.

**Comment by XX-Yin** [comment]
> > @alexpiet What's exactly your concern? It's just an extra parameter.
> 
> Its not just this one parameter. Its the multiplicative effect of extra parameters, code blocks, and functions. If we want to update something we have to check more cases and conditions.

@alexpiet You removed this important functionality before and now it's just to restore it. Also, the streamlit doesn't support visualization in different resolution right now (it seems to be difficult to achieve this in the streamlit). We should also ensure that the GUI is functionally complete in terms of basic visualization and other basic functions. In the future, individuals outside of this institute who wish to replicate our behavioral setup won’t have access to the daily Streamlit updates. However, they should still be able to use the GUI to monitor the training data.

**Comment by alexpiet** [comment]
Lets merge this in, because we both agree kernel size of 10 is better than 2. 

Then we can continue this discussion. My point is that the GUI shouldn't be a tool for basic visualization! The GUI should be for data acquisition

**Comment by XX-Yin** [comment]
> Lets merge this in, because we both agree kernel size of 10 is better than 2.
> 
> Then we can continue this discussion. My point is that the GUI shouldn't be a tool for basic visualization! The GUI should be for data acquisition

This is important to make a complete update here!! We need basic visualization for the GUI for normal monitoring and visualization. The choice visualization we are currently updating here is basic enough. How do you define the basic visualization?

**Comment by alexpiet** [comment]
@XX-Yin I moved this discussion to a separate issue: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/955

**Pull request merged**
