### PR TITLE
Finished warm up

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "production_testing" into "main" should use the keyword "production merge" in the title for reliable indexing of updates
  
### Describe changes:
1) Added warning to show metrics and state related to warm up. 
2) Fixed a bug related to the finish length. 

### What issues or discussions does this update address?
Resolves: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/213#issuecomment-1921951325
Resolves: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/177#issuecomment-1917698175

### Describe the expected change in behavior from the perspective of the experimenter
If the warmup is turned on (typically for the first session of a mouse), the session starts with previous Coupled-Baiting Stage 1.1

image

After warmup termination criteria are met, goes back to normal training, i.e., parameters before warmup
image

 

### Describe the outcome of testing this update on a rig in 447
Tested on my own computer.

### CODE REVIEW

**Comment by XX-Yin** [comment]
This is the warning.
image

**Comment by hanhou** [comment]
It looks great now!

**Review by hanhou — APPROVED** [review]

**Comment by hanhou** [comment]
Just notice another bug: we should cache the `Task` before warmup. During warmup, task should be set to "Coupled Baiting". After warmup, we should then recover `Task` as well.

**Review by hanhou — CHANGES_REQUESTED** [review]
please also cache, set, and restore `Task`

**Comment by XX-Yin** [comment]
> please also cache, set, and restore `Task`

Very good catch! I updated it!

**Review by hanhou — APPROVED** [review]
It looks good now. The only remaining things in my [wishlist](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/146#issue-2071349341) is making `warmup_block_length` and `warmup_reward_probs` adjustable so that it could be a general-purpose warmup part, not just for the first session. But it is good enough for now.

**Comment by XX-Yin** [comment]
> It looks good now. The only remaining things in my [wishlist](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/146#issue-2071349341) is making `warmup_block_length` and `warmup_reward_probs` adjustable so that it could be a general-purpose warmup part, not just for the first session. But it is good enough for now.

Yes, it's fixed. We can make changes if we need it in the future.

**Pull request merged**
