### PR TITLE
Metadata not saved

### PR DESCRIPTION
**Pull request by micahwoodard**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
- changing variables from type np.float64 to float type
### What issues or discussions does this update address?
- resolves [#799](https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/799)
### Describe the expected change in behavior from the perspective of the experimenter
- metadata can now be saved without error on 6D
### Describe any manual update steps for task computers
- None
### Was this update tested in 446/447?
- [ ] 477 specifically on 6D

### CODE REVIEW

**Comment by micahwoodard** [comment]
@XX-Yin would be helpful if you could test this on the computers you were seeing issues on to confirm it's the same issue

**Comment by XX-Yin** [comment]
It’s only on 6D. Thanks for fixing this issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by micahwoodard** [comment]
Okay great could you approve so I can merge?

**Review by XX-Yin — APPROVED** [review]

**Comment by micahwoodard** [comment]
as a note also tested on 8D

**Pull request merged**
