### PR TITLE
[do not merge] updating gui layout

### PR DESCRIPTION
**Pull request by alexpiet**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "production_testing" into "main" should use the keyword "production merge" in the title for reliable indexing of updates
  
### Describe changes:
This is a small update to the layout of the GUI. I am only moving boxes around to remove white space and condense the size of the GUI. 

### What issues or discussions does this update address?
- https://github.com/AllenNeuralDynamics/aind-behavior-blog/discussions/102

### Describe the expected change in behavior from the perspective of the experimenter
The GUI will have a more compact layout

MicrosoftTeams-image4377fb35a2b7c24bb898d423395abf0c4e52cca4c96952b70bde167944d51163

### Describe the outcome of testing this update on a rig in 447
- [ ] tested in 447

### CODE REVIEW

**Comment by XX-Yin** [comment]
It is better to make the layout of the GUI dynamic (changeable). The smaller GUI is only preferable in the training rig where the screen is limited so far. I will prefer to use the current GUI in the ephys rig where we have enough space to show more information.

**Comment by alexpiet** [comment]
@XX-Yin What do you mean by dynamic?

This update does not remove any information from the screen, it just reorganizes it to be more compact.

**Comment by XX-Yin** [comment]
What I have in mind is that we could have two layouts (one for training rig and one for ephys rig). And these two layouts can be changed freely in the GUI. 

Your current layout condensed the visualization and basic information panel.

**Comment by alexpiet** [comment]
@XX-Yin I see, so you are suggesting we add a button to the GUI that toggles between a condensed view (training room), and more elaborate view (ephys rigs). That seems like a good suggestion. Can you implement that? I think a streamlined GUI is a high priority for the RAs, and you are much more familiar with Qt designer than I am

**Comment by hanhou** [comment]
Maybe a responsive UI design can be helpful? Compare the difference sizes of the same AutoTraining dialog:
image

**Comment by alexpiet** [comment]
Yes, tabs would be good.

**Comment by XX-Yin** [comment]
We can improve the GUI layout in two parts.
1) One is to switch between two layouts through buttons.
2) Another is to use tabs like Han suggested to save space.

The two approaches are not exclusive.

Yes, I can try to make some changes.

**Pull request closed without merging**
