### PR TITLE
[skip email] updating soundcard package

### PR DESCRIPTION
**Pull request by alexpiet**
- Updates `Harp.SoundCard` bonsai package to `0.2.0`
- After merging, run `dynamic-foraging-task/bonsai/setup.cmd` to install the new package
   - [ ] 446 @XX-Yin @ZhixiaoSu 
   - [ ] 447 @XX-Yin @ZhixiaoSu 
   - [ ] 428 @hagikent 
   - [ ] Ephys1 @KanghoonJ 
   - [ ] Ephys3 @XX-Yin 
- This is a hot fix because the SoundCard package was manually updated in the 447 computers through the bonsai IDE, which leads to inconsistencies in the `Bonsai.config` file. We are updating the `Bonsai.config` file to make sure all rigs are consistent.

### CODE REVIEW

**Comment by ZhixiaoSu** [comment]
@hagikent Thank you for the super helpful information! This manual installation seems to be compatible with main behavior workflow when @XX-Yin and I tested yesterday. (Sound player normally and attenuation changed tone level.) Will adding the package manually affect the daily refresh at 6 am?

**Comment by hagikent** [comment]
>affect the daily refresh at 6 am?

No, but the manually added package will be pushed back to 0.1.0 next 6am.
With a minor (yellow) alert from RoboAlex.
Screen Shot 2024-07-03 at 11 55 25

**Comment by alexpiet** [comment]
What is strange is that the update this morning *didn't* reset the repo. The bonsai/bonsai.config file had untracked changes after the 6am update.  Completely unclear to me why this happened. I manually reset the 447 computers, but it was a mysterious process. I recompiled bonsai, and did a `git pull origin main` in the command line, which somehow worked. I'll close this PR for now, but in the future, when installing new bonsai packages we need to ensure there are no untracked changes.

**Comment by hagikent** [comment]
Hmm, that's mysterious... never happened to me at 446/428, where I did this manual package adding >50times.

**Comment by alexpiet** [comment]
Actually, now that I look. This warning is in the logs for 446. Maybe because no one has run mice they haven't been noticing

**Comment by alexpiet** [comment]
I updated all the 446 computers except 7CD because IT is doing something remotely

**Comment by hagikent** [comment]
Yes, Ian from IT is working on 7C, trying to solve the Soundcard compatibility issue.

**Pull request closed without merging**
