### PR TITLE
Adding 5 second delay before stopping fip and remove extra pop up 

### PR DESCRIPTION
**Pull request by micahwoodard**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
- Stops redundant stop popup and delays fip on automatic stop
### What issues or discussions does this update address?
- resolves issues mentioned in #805 
### Describe the expected change in behavior from the perspective of the experimenter
- if automatic stop is triggered, fip will stop after 5 seconds and session will go through stopping logic
### Describe any manual update steps for task computers
- None
### Was this update tested in 446/447?
- [ ] 446/7

### CODE REVIEW

**Comment by alexpiet** [comment]
> I've just been testing at 447, and @ellahiltonvano showed me that the aind stage can already upload the last stage position of a mouse ? @alexpiet or @jessy-liao does anyone know where this is already happening? I can't find where it is

Did you mean to ask that on this PR? I have no idea where the aind stage would be recording the position

**Comment by micahwoodard** [comment]
Oh darn sorry no I will move this so it makes more sense.

**Review by alexpiet — APPROVED** [review]
Feel free to merge after testing in 446/447

**Comment by micahwoodard** [comment]
I'm deleting this for a new branch. I don't think I actually need to call _Start to implement the stopping logic so I'm just going to add a 5 second delay to stopping fib

**Pull request closed without merging**
