### PR TITLE
Only logging error for fip if mouse training stage is at certain point

### LINKED ISSUE #1045: Update FIP schedule check to use "First FP Stage"
If the schedule shows:
FP		Axon	FINAL

Then don't send an alert for starting the session without FIP unless the mouse is on "FINAL"

### PR DESCRIPTION
**Pull request by micahwoodard**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
- check schedule for what stage mouse will start fip and only log errors for fip if mouse training stage is at certain point
### What issues or discussions does this update address?
- resolves #1045 
### Describe the expected change in behavior from the perspective of the experimenter
- None
### Describe any manual update steps for task computers
- None
### Was this update tested in 446/447?
- [x] 446

### CODE REVIEW

**Comment by micahwoodard** [comment]
Functionality should be if First FIP Stage is greater than current stage, no warning will appear. If First FIP Stage is undefined and FIP mode is specified, warning will appear. If autotrain has no specified stage and FIP mode is specified, warning will appear regardless of First FIP Stage.

**Review by alexpiet — APPROVED** [review]
This works. Its a little bit of a brittle solution since it:
(1) will break if the number of stages changes, or the names of the stages change
(2) depends on a convention of how information is stored in the schedule.

@hanhou @ellahiltonvano any input?

**Comment by ellahiltonvano** [comment]
@alexpiet (theoretically) we agreed to have the schedule naming convention match autotrain. I think that is now happening in all cases. 

I do think this will be helpful, there have been mice run under the incorrect curriculum. But I agree that it will likely need to be updated as we iterate through curriculum changes.

**Comment by micahwoodard** [comment]
> @micahwoodard if first FP stage is unspecified this means RAs start FIP at stage 1, fyi

in the streamlit app or just in the schedule? 

> @micahwoodard if first FP stage is unspecified this means RAs start FIP at stage 1, fyi. I also think it would make sense to pull training stage information from Streamlit, rather than relying on RAs to update the schedule (this gets missed a fair bit)
 
The training stage info is being pulled from the AutoTrain_dialog which I believe is relying on the Streamlit app, not on the schedule.

**Comment by ellahiltonvano** [comment]
@micahwoodard on the schedule

**Comment by micahwoodard** [comment]
> @micahwoodard on the schedule

Oh sorry I read your comment wrong that makes total sense and the logic should follow that

**Comment by micahwoodard** [comment]
> This works. Its a little bit of a brittle solution since it: (1) will break if the number of stages changes, or the names of the stages change (2) depends on a convention of how information is stored in the schedule.
> 
> @hanhou @ellahiltonvano any input?

@alexpiet any thoughts on how to make it less hardcoded? It would probably be a good idea to put in some checks to make sure nothing breaks if the schedule has an unexpected value. I could also populate the stages list programmatically if there is anywhere that stores that info.

**Comment by micahwoodard** [comment]
@alexpiet do we want to merge this in for this week or wait for a more flexible solution

**Comment by alexpiet** [comment]
@micahwoodard Sorry I didn't respond promptly. I would merge it in. As we adopt data models and the new training curriculum manager we can make this more flexible

**Pull request merged**
