### PR TITLE
show sessions with old format

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
Make the GUI can load sessions with old folder structure to the session list. 
image

### What issues or discussions does this update address?
The old session with a different folder structure cannot be loaded to the session list. 

### Describe the expected change in behavior from the perspective of the experimenter
No

### Describe any manual update steps for task computers
No

### Was this update tested in 446/447?
Tested on my own computer

### CODE REVIEW

**Comment by alexpiet** [comment]
Do you have any active mice that use the old folder structure? Why incorporate this feature?

**Comment by XX-Yin** [comment]
> Do you have any active mice that use the old folder structure? Why incorporate this feature?

Yes, we have collected data with old structure that can't be displayed in the session list.

**Comment by alexpiet** [comment]
But isn't that data from more than several weeks ago? I assume that means its from non-active mice. If that is the case, then why are you viewing it on the GUI?

**Comment by XX-Yin** [comment]
> But isn't that data from more than several weeks ago? I assume that means its from non-active mice. If that is the case, then why are you viewing it on the GUI?

Yes, that data is several weeks ago. 

Sometimes, it's more straightforward to check parameters and behavior performance of that session from the GUI.

**Comment by hanhou** [comment]
FYI, the 'Streamlit!' button now opens all training history of current mouse right away. See this PR https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/432

**Comment by XX-Yin** [comment]
@alexpiet @hanhou 
This PR has no harm to the main code. Just an additional function.

**Review by alexpiet — APPROVED** [review]

**Pull request merged**
