### PR TITLE
Camera windows merge; Real-time lick visualizaton

### PR DESCRIPTION
**Pull request by hagikent**
1.HighSpeedCamera windows are merged into one
2.Real time L/R licking visualization added
  
### Describe changes:
**1. HighSpeedCamera windows are merged into one**
This is inside of the RestartLogger `create observables`.

Visualizer_HighSpeed

**2.Real time L/R licking visualization added**
This is inside workflow->visualization
Visualizer_Lick

For now, I cannot merge two windows into the same.
Anyone knows how (or if possible) to publish image visualizer from `create observables`  to outside so that they can be fed into the same `visualizer mapping`? @bruno-f-cruz 

### What issues or discussions does this update address?
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/559
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/499

### Describe the expected change in behavior from the perspective of the experimenter
You will see the following new bonsai visualizer windows.
window

### Describe any manual update steps for task computers
NA

### Was this update tested in 446/447?
- [x] 428 by @hagikent 
- [x] 446/447 (in 447, only LickVis is relevant as no highspeedcam installed yet)
- [ ] Ephys (not yet expanded to new Lickety-split lick-o-meter, though; Let me know if I should generalize now @XX-Yin @galenlynch )
- [ ] etc

### CODE REVIEW

**Comment by ZhixiaoSu** [comment]
This branch is tested on 446 6A and worked well both in and outside of task (please check picture below). The only manual change needed was to install pyyaml package. 
Image (6)

**Comment by hagikent** [comment]
Thanks @ZhixiaoSu ! Can you please approve the PR too?

>pyyaml

Not for those changes; this branch was forked from `development` and it already required pyyaml.
I suppose some metadata-related PR from @XX-Yin or @alexpiet ? Haven't checked, though.

**Review by ZhixiaoSu — APPROVED** [review]
Branch works as expected in 446, box 6A.

**Comment by hagikent** [comment]
yaml is from #566 and will be merged into main this week

**Pull request merged**
