### PR TITLE
Fix behavior modality in upload manifest

### LINKED ISSUE #1114: Upload manifest issues
It appears there are multiple issues related to data upload. This appears to only being happening on the production_testing branch
- Saved data is stored at `behavior_behavior_<mouse_id>_<date time>` instead of `behavior_<mouse_id>_<date time>`
- The behavior modality is not accurately being added to the upload manifest

### LINKED ISSUE #1123: Upload manifest/session metadata does not register behavior video when video is started through FIP workflow

### PR DESCRIPTION
**Pull request by alexpiet**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
Always adds the behavior modality, instead of checking stream_modalities which had behavior removed as a modality

### What issues or discussions does this update address?
- resolves #1114 
- resolves #1123

### Describe the expected change in behavior from the perspective of the experimenter
- none

### Describe any manual update steps for task computers
- none

### Was this update tested in 446/447?
- [x] tested in 447

### CODE REVIEW

**Comment by alexpiet** [comment]
@XX-Yin This is ready for review, and replaces #1116

**Comment by XX-Yin** [comment]
@alexpiet 
The way to check the modality has two issues:
1) The video modality will not be added to the manifest file as the video streams will only be added to the session streams when there is an end time detected. 
2) The current code would only generate manifest file in the first trial and could miss modality started after first trial. 

I know that you thought the point 2 is not an issue. Please make changes to the point 1 to make the modality check more robust. I suggest we directly check the folder empty for each modality instead of using the session streams.

**Comment by alexpiet** [comment]
Why is the video only added to the stream modalities when there is an end time, but the FIP is added before there is an end time?

**Comment by XX-Yin** [comment]
It's a history issue. You can also change the video modality to be like the FIP

            if hasattr(self, 'fiber_photometry_start_time'):
                Obj['fiber_photometry_start_time'] = self.fiber_photometry_start_time
                if hasattr(self, 'fiber_photometry_end_time'):
                    end_time = self.fiber_photometry_end_time
                else:
                    end_time = str(datetime.now())
                Obj['fiber_photometry_end_time'] = end_time

**Comment by alexpiet** [comment]
@XX-Yin what about this update

**Comment by XX-Yin** [comment]
> @XX-Yin what about this update

This works. 

1) Can you also remove the `camera_start_time` and `fiber_photometry_start_time` when starting a session(like I did in https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/1116/files#diff-b3cf4ca4fc9cb05d0a854615b8178bb10c1805e102fa1685fd60bd66bec9d34aR4052)?  Otherwise, it may interact with the next session. 
2) And don't delete the `fiber_photometry_start_time` at here https://github.com/AllenNeuralDynamics/dynamic-foraging-task/pull/1116/files#diff-b3cf4ca4fc9cb05d0a854615b8178bb10c1805e102fa1685fd60bd66bec9d34aL3628. Otherwise, it may not generate the fiber photometry data stream after the new session button is clicked (e.g. after saving). 
3) Can you also make changes in the fiber photometry data stream in the GeneratedMetadata.py to keep consistent with the behavior video data stream?

**Comment by alexpiet** [comment]
Those seem like separate issues from the upload manifest modality.

**Comment by XX-Yin** [comment]
At least the first one is directly associated the manifest file as the code is using the Session Metadata to get the modalities.

**Comment by alexpiet** [comment]
But I'm not setting the start time for the camera or photometry in either the metadata or the window object.

**Comment by XX-Yin** [comment]
If the previous session has the `camera_start_time` and `camera_end_time` and the current session doesn't have the video stream and we don't restart the GUI, the video stream will be added to the current session. I think the root issue is from the session metadata, but it will also influence the modality detection in the manifest file.

**Comment by alexpiet** [comment]
I just tried it, and that does not happen

**Comment by alexpiet** [comment]
Although that may be a result of this bug I just found: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/1123

**Comment by XX-Yin** [comment]
> I just tried it, and that does not happen

Did you click the start recording (not the preview)?

**Comment by alexpiet** [comment]
No, I recorded video through the FIP workflow. I just fixed #1123. I will check in 446 and just record video

**Comment by alexpiet** [comment]
Commented on the wrong PR:

Ok, you are right that if you run a session with the camera, and then start a new session without the GUI, then it incorrectly lists behavior-video as a modality in the manifest and in the session metadata. I'll make a separate issue, since I don't have time to fix that right now. Lets merge this fix in, since it will effect every session
here is the issue: https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/1124

**Comment by alexpiet** [comment]
@XX-Yin do you have any remaining concerns?

**Comment by XX-Yin** [comment]
@alexpiet We can first merge this and fix other issues

**Review by XX-Yin — APPROVED** [review]

**Pull request merged**
