### PR TITLE
Updating organization of data folder

### PR DESCRIPTION
**Pull request by alexpiet**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
The data being saved by the GUI will now have the following format:
- [x] root folder name: `behavior_<mouse>_<date>_<time>`
    - [x] PhotometryFolder - > `fib`
    - [x] EphysFolder -> `ecephys`
    - [x] VideoFolder -> `behavior-videos`
    - [x] TrainingFolder -> `behavior`
    - [x] HarpFolder -> add to behavior as subfolder named `raw.harp`
    - [x] `metadata-dir`, folder with:
        - data_description.json
        - subject.json
        - rig.json
        - session.json
        - processing.json
        - procedures.json
- [x] Removes unused `Foraging._GetSaveFileName"
- [x] Remove CPhotometryFolders and similar flags, since we always create the folders
- [x] In order to handle backwards compatibility in loading, I created some temporary code that should be removed in the future: #300 

### What issues or discussions does this update address?
- resolves https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/298

### Describe the expected change in behavior from the perspective of the experimenter
- None

### Describe the outcome of testing this update on a rig in 447
- [x] tested on my laptop
- [x] tested to ensure backwards compatibility when loading data
- [ ] tested in 447
- [ ] tested with FIP
- [x] Need to make sure bonsai workflow is updated as well

### CODE REVIEW

**Comment by hagikent** [comment]
>metadata-dir
I believe @dyf 's description was "all metadata on the root of each session folders".

**Comment by alexpiet** [comment]
> > metadata-dir
> 
> I believe @dyf 's description was "all metadata on the root of each session folders". So, this subdir should be eliminated.

@hagikent and I asked @dyf about this, and he said "For uploading purposes, put all json metadata in it's own folder. They will be shuffled around by the data transfer service."

**Comment by alexpiet** [comment]
@hagikent @hanhou @XX-Yin This is ready for review

**Comment by hanhou** [comment]
I did a test and it looks good.

**Review by hanhou — APPROVED** [review]

**Pull request merged**
