### PR TITLE
Feat 296 bias indicator

### PR DESCRIPTION
**Pull request by micahwoodard**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"

### CODE REVIEW

**Comment by alexpiet** [comment]
back merging to keep consistent with main

**Comment by XX-Yin** [comment]
@micahwoodard There are some new packages required for the update. Smrithi and I didn't realize this, so we ran into some issues at first. Please notify individuals if there are some local updates.

**Comment by XX-Yin** [comment]
Smrithi also found there are package conflicts when trying to install these new packages. Smrithi will submit a github issue.

**Comment by alexpiet** [comment]
@XX-Yin The updates were tested to be installable with `pip install -e .`. That command runs as part of the automatic update script, so if the update script is enabled then the update should work without manual steps. What rig did you have problems on? Are you using the update script? What issues did you encounter?

**Comment by XX-Yin** [comment]
It seems the `pip install -e .` did not run automatically in the ephys rig 3 and Smrithi's rig. Smrithi had the `package conflict error` when trying to run `pip install -e` in a new python environment. Smrithi will document the error in details tomorrow.

**Pull request merged**
