### PR TITLE
 Changed the codec

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "production_testing" into "main" should use the keyword "production merge" in the title for reliable indexing of updates
  
### Describe changes:
Changed the codec used to compress video online in bonsai. 
before: -vcodec libx264 -crf 23 -preset medium -threads 10
after: -vcodec h264_nvenc -crf 23 -preset medium
### What issues or discussions does this update address?
Resolves https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/189#event-11593005192

### Describe the expected change in behavior from the perspective of the experimenter
No

### Describe the outcome of testing this update on a rig in 447
Tested in the ephys rig. It was running without memory accumulation. 

- [ ] test the compression quality

### CODE REVIEW

**Review by alexpiet — APPROVED** [review]

**Comment by alexpiet** [comment]
Assuming the compression quality is acceptable!

**Comment by XX-Yin** [comment]
Based on video collected today, the quality of this new codec was obviously worse than the previous codec. We are testing with lower compression rate.

**Comment by XX-Yin** [comment]
I tried  `-vcodec h264_nvenc -crf 0 -preset medium`. The video is still blurry. Keep @bruno-f-cruz updated!

**Comment by bruno-f-cruz** [comment]
Any reason to have crf 0?

**Comment by XX-Yin** [comment]
I tried crf 23, and the video was blurry especially when animal was moving. So, I hope to try some lower crf that means higher quality and larger data size. I also tried crf 1 and it didn't seem to make a big difference.

**Comment by XX-Yin** [comment]
Yeah, maybe it has something to do with the frame rate. I can try some other parameters with this codec. I haven't tested other GPU codecs. One thing we should remember is that problems only arise when the animal moves.

**Comment by XX-Yin** [comment]
I deleted the raw data as it's too large. It seems that @ZhixiaoSu recorded some raw video. If not, I can record 1m for you.

**Comment by ZhixiaoSu** [comment]
Yes, I got some raw video but haven't tried compression yet. They are in scratch\sueSu\cameraTest\ephysRig. (Being transferred there now.)

**Comment by XX-Yin** [comment]
Sue and I tried codec  `-vcodec libx264 -crf 23 -preset fast`. The video quality is good, with no obvious blurring. We plan to use this codec. One thing we found is the data size is related to the illumination. Higher illumination resulted in larger data size, which may reflect greater detail in higher illumination.

**Pull request merged**
