### PR TITLE
enable harp register dump

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
Enable the harp register dump

### What issues or discussions does this update address?
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/461

### Describe the expected change in behavior from the perspective of the experimenter
No

### Describe any manual update steps for task computers
No

### Was this update tested in 446/447?
- [x] tested on my own computer
- [ ] tested in 323_Ephys3

### CODE REVIEW

**Comment by XX-Yin** [comment]
Found the same error I saw before when the new lick detector was connected, and the register dump was enabled.

**Comment by alexpiet** [comment]
> Found the same error I saw before when the new lick detector was connected, and the register dump was enabled.

Do you mean that enabling the harp register dump creates an error? What is the error?

**Comment by XX-Yin** [comment]
Yes. Will post the error later

**Comment by XX-Yin** [comment]
Error information:
Image

**Comment by alexpiet** [comment]
@XX-Yin Can you post the log file? It looks like there is another error happening above. Can you ask @bruno-f-cruz for advice?

**Comment by bruno-f-cruz** [comment]
This is an error outside bonsai. Seems related with the way you are parsing data. Are you excluding read messages from your client software? The readdump will produce a read message from all registers, if your client is not prepared to deal with these I can see a world where this error makes sense

**Comment by XX-Yin** [comment]
> deal

I don't exclude the read messages. This seems to be the issue.

**Comment by alexpiet** [comment]
Closing as stale

**Pull request closed without merging**
