### PR TITLE
Add one trial for no response

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
1. Added a selection `add one trial for no response` to the UI. It is set to `Yes` by default. 
image
2. When the `add one trial for no response` is selected as `Yes`, it will add one trial to the block length on both sides. 

### What issues or discussions does this update address?
https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/439

### Describe the expected change in behavior from the perspective of the experimenter
Select the `add one trial for no response` as `No` if you don't want to turn off this function.

### Describe any manual update steps for task computers
No

### Was this update tested in 446/447?
Tested on my own computer.

### CODE REVIEW

**Comment by ZhixiaoSu** [comment]
Thank you for adding this feature! The related issue is here https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/439
So, with this change: 
Does it mean this choice is only manual? If we do that, it will put the animal off-curriculum. Or we will need to add a field to all auto-training curriculums And what's the reason of keeping it 'No' as default?

**Comment by XX-Yin** [comment]
> Thank you for adding this feature! The related issue is here [AllenNeuralDynamics/aind-behavior-blog#439](https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/439) So, with this change: Does it mean this choice is only manual? If we do that, it will put the animal off-curriculum. Or we will need to add a field to all auto-training curriculums And what's the reason of keeping it 'No' as default?

Ok, I can set it `Yes` by default. 

When I am doing optogenetics, some effects are "increased no response rate" and I don't want an additional trial. I can manually change this for my mice.

**Comment by ZhixiaoSu** [comment]
Got it! This sounds more like something to be taken care of in the data acquisition period after being well-trained. If this is the case, maybe it makes sense to have an optogenetics curriculum so that the graduation+opto stage has this field to be 'No'?

**Comment by XX-Yin** [comment]
@ZhixiaoSu Updated. The default was set to `Yes`

**Review by KanghoonJ — APPROVED** [review]

**Comment by ZhixiaoSu** [comment]
7/9/2024: Branch tested on 446 6A. Session runs normally, and block length gets longer by 1 trial on both sides when animal does not respond. Tested task: uncoupled unbaited.

**Pull request merged**
