### PR TITLE
Bias Indicator

### PR DESCRIPTION
**Pull request by micahwoodard**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
- added widget that calculates and graphs logistic regression bias of licks
### What issues or discussions does this update address?
- [#296](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/296) 
### Describe the expected change in behavior from the perspective of the experimenter
- graph tracking bias will be visible
### Was this update tested in 446/447?
- [x] 446

### CODE REVIEW

**Comment by alexpiet** [comment]
Wow, looks great!

My immediate reaction is that the bias plot is taking up too much space. Can you make it smaller horizontally? Like maybe 2/3rds or 1/2 of the current width?

**Comment by micahwoodard** [comment]
> Wow, looks great!
> 
> My immediate reaction is that the bias plot is taking up too much space. Can you make it smaller horizontally? Like maybe 2/3rds or 1/2 of the current width?
> 
> Right now I think you are computing the bias on every trial, and using the last 15 trials to compute the bias. And then only plotting the bias from the last 15 trials. @hanhou What do you think of that?
> 
> I think we generally want Left to be the top, and Right to be the bottom

Oh I thought we were switching the right and left on the other graph so that's why I had it configured like this. I can definitely swap those though. Just to double check, a positive bias value correlates to right: negative, left?

**Comment by hanhou** [comment]
>  I'm just using randomly generated numbers to calculate bias so it would be nice to test maybe with an actual mouse?

In the drop down menu "Tools" you can find a simulator which can simulate animal behavior (use the win-stay-lose-shift one)

**Comment by alexpiet** [comment]
> > I think we generally want Left to be the top, and Right to be the bottom
> 
> Oh I thought we were switching the right and left on the other graph so that's why I had it configured like this. I can definitely swap those though. Just to double check, a positive bias value correlates to right: negative, left?

Well, I can't remember what should be on top. I just noticed the bias is plotted the opposite of the plots on the left, but I guess you haven't flipped those yet. Sorry for the confusion.

The sign of the bias depends on how you called the logistic regression function. When you call it, if right choices are = 1, then positive bias will mean right bias. If left choices are = 1, then positive bias will mean left bias. I think, and @hanhou can confirm, that the code always uses right=1 by convention

**Comment by hanhou** [comment]
> Right now I think you are computing the bias on every trial, and using the last 15 trials to compute the bias. And then only plotting the bias from the last 15 trials. @hanhou What do you think of that?

I would keep track two biases: a global bias computed from trial 1 to trial N of a session, and a local bias from trial N-M to trial N. In my proposed algorithm, the lickspout movement is driven by the local bias, and I use M = 500 (which could span to previous session). I don't know the best hyperparameters, and we have to try. But in general, M should be larger than ~ 200 trials so that the bias estimate is more accurate

image

**Comment by hanhou** [comment]
> We could take some existing data and compute the bias from it (maybe @hanhou already has this somewhere)

Yes, we should do some simulation with existing data. I only computed global bias for each session, as shown in the streamlit app:

image

The overall distribution is like this:

image

It looks like logistic regression sometimes failed ending up with very large biases.

**Comment by micahwoodard** [comment]
@hanhou and @alexpiet do have a minute today to chat about steps forward for this? It would be nice to get some clarity implementation of the global and local biases and testing the best parameters for the regression. I am free anytime today if either of you have a minute.

**Comment by alexpiet** [comment]
Conversation with @micahwoodard, and we decided for the first pass implementation:
- don't compute global bias. @hanhou Its not clear why we need this in the GUI.
- use 0.7 as bias threshold, but seek feedback from RAs whether this matches their intuition
- use M=500 for number of trials to compute bias over. Seek feedback from RAs whether this is jittery or sluggish compared to their intuition
- Compute the bias every 10 trials, this is probably overkill, but just to get a sense of the data
- In the first 0 to M trials, compute the bias over just the trials in this session, since figuring out bias from the last session is (1) hard to implement, (2) unclear scientific value (do mice track bias over days?)
- Probably move bias computation to a separate thread if its slow to compute with M=500
- Long term we would like to store the bias along with other trial history information. I dont know how thats organized or implemented, so I advised @micahwoodard she might want to skip that for the first pass while we figure out the issues above. She should follow up with @XX-Yin about how to organize that information.

**Comment by micahwoodard** [comment]
Okay @alexpiet and @hanhou  this is ready to be reviewed again. I've implemented the changes Alex mentioned above. One thing I did want to draw attention to is that I was having difficulties calculating bias if the trial count was too similar to the n_trial_back parameter. To handle this, I am setting n_trail_back to be 60% of the trial count before 500 trial. I tried to explain what I'm doing in [this comment](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/1fcccc1603707fd4a77191f4abe17171aa2cf8da/src/foraging_gui/Foraging.py#L4199C21-L4201C104). Let me know if there is a better way to handle this. 

Also, another this I wanted to note is that now I am plotting the bias as [bias, trial_count] instead of [bias, bias_count].  I also added logging statements noting bias and trial_count. I changed this so it would be easier to look back on the logs and see the bias trend through out the session. Let me know if this isn't what you envisioned. 

Thanks and hope you have a great weekend!

**Comment by alexpiet** [comment]
@micahwoodard Looks great, a have a handful of cosmetic details to address. But I'll merge it and we can get feedback from the RAs and iterate from there

**Review by alexpiet — APPROVED** [review]

**Comment by XX-Yin** [comment]
@micahwoodard There is an error information when using the ForagingGUI_Ephys.ui. Can you take a look?

**Comment by micahwoodard** [comment]
@XX-Yin do you want me to come take a look right now at the Ephys rig for the error information? If so where are the ephys rigs, I've never been to those. Is it like a logging error?

**Comment by XX-Yin** [comment]
@micahwoodard You don't need to test it on the Ephys rig. And this error can be replicated in the main branch if you open the `ForagingGUI_Ephys.ui` GUI by changing the `default_ui` to `ForagingGUI_Ephys.ui` in the `ForagingSettings.json` file. I'm also happy to show you on my own computer if you can't replicate this error.

**Pull request merged**
