### PR TITLE
Update random method

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
1. Enable to set the randomness methods (even and exponential distribution) separately for block length and ITI/Delay. 
2. Updated the NWB file to include the randomness fields.
3. The uncoupled task hard-coded the randomness methods for block length as `even`. The update allows us to control the randomness of the uncoupled tasks from the GUI.

### What issues or discussions does this update address?
https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/542

### Describe the expected change in behavior from the perspective of the experimenter
1. The curriculum may need updating in the future (@hanhou). The `Randomness` was moved and updated with two fields called `RandomnessBlock` and `RandomnessOther`. If not provided, `RandomnessBlock` and `RandomnessOther` will default to `Even` and `Exponential` respectively.

### Describe any manual update steps for task computers
No

### Was this update tested in 446/447?
- [x] tested on my own computer

### CODE REVIEW

**Comment by XX-Yin** [comment]
@KanghoonJ @ZhixiaoSu 

The `block distribution` of the `uncoupled task` was set to `Even` by default (hardcoded by @hanhou). I updated the code to explicitly set the `block distribution` and `ITI/delay distribution` independently for all tasks.

**Comment by XX-Yin** [comment]
@hanhou @alexpiet @ZhixiaoSu @KanghoonJ This is ready for review.

**Comment by XX-Yin** [comment]
> 2\. hazard

Hi Han, the idea is to allow us to set the distribution of all tasks from the GUI. 

1. I agree to use the uniform distribution for block length in uncoupled task. 
2.  For coupled tasks, it may be better to use a uniform distribution, too. 1) It will let us get more longer blocks during analysis. 2) If it's left-skewed exponential distribution, animals may perceive the block more as `short blocks` and develop strategies good for short blocks.

**Comment by hanhou** [comment]
If your main concern is that blocks are too short, you can increase beta to make them more even. I think this is a major change to the task, and we should discuss it more thoroughly before changing it. Could you add a discussion point to the next behavior meeting?

Also, changing the name will break lots of downstream pipeline, especially considering that during the production_test phase there are different rigs running on different codebases. Could you still use `Randomness` for blocks (default = `exponential`) and `RandomnessOther` for ITI etc (default = `exponential` too)?

**Comment by XX-Yin** [comment]
@hanhou 
`downstream pipeline`, are you mainly meaning the `NWB` and `Curriculum`? 

For `NWB`, we don't have the `Randomness` field stored in the old version. I updated the NWB to add the `Randomness` to different versions of behavior json. 

For `Curriculum`, if the `Randomness` is not detected as a GUI field, will an error occur? Or just ignored.

**Comment by hanhou** [comment]
> For Curriculum, if the Randomness is not detected as a GUI field, will an error occur? 

Looks like we're fine in this case https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/2fea58cc170beb75d6d92e31a9d7253e26c6bf57/src/foraging_gui/Dialogs.py#L2989

But please make sure that both are set to `exponential` by default for maximum backward compatibility.

**Comment by XX-Yin** [comment]
> > For Curriculum, if the Randomness is not detected as a GUI field, will an error occur?
> 
> Looks like we're fine in this case
> 
> https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/2fea58cc170beb75d6d92e31a9d7253e26c6bf57/src/foraging_gui/Dialogs.py#L2989
> 
> But please make sure that both are set to `exponential` by default for maximum backward compatibility.

@XX-Yin 
I think the distribution of block length in the uncoupled task was hardcoded to `uniform`. 

I will set the `block distribution` for `uncoupled task` to `uniform`, and for `coupled task` to `exponential` by default. 
And set the `ITI and delay distribution` to `exponential` by default.

**Comment by XX-Yin** [comment]
@hanhou We can hold off this pull request until the curriculum is updated. Setting default block lengths for different tasks would complicate the logic and be easy to make mistakes.

**Comment by hanhou** [comment]
> I think the distribution of block length in the uncoupled task was hardcoded to uniform.

Oh, yes. But I still think we'll never use exponential block length in uncoupled task since it will further complicate the distribution of the "effective block length" in the uncoupled task. @ZhixiaoSu what do you think?

**Comment by alexpiet** [comment]
Closing as stale

**Pull request closed without merging**
