### PR TITLE
 fix loading water

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "production_testing" into "main" should use the keyword "production merge" in the title for reliable indexing of updates
  
### Describe changes:
Load the water information from the json file. 
Water information will be loaded from the previous json file and cleared after Start. 

### What issues or discussions does this update address?
Resolves: https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/238

### Describe the expected change in behavior from the perspective of the experimenter
No. 

### Describe the outcome of testing this update on a rig in 447
Tested on my computer

### CODE REVIEW

**Review by alexpiet — COMMENTED** [review]
Can you clarify what information will be present, and when? There was discussion on the issue about the best solution and its not clear exactly what you implemented. A screen shot would probably be sufficient.

**Comment by XX-Yin** [comment]
This is the updated version. It will load all weight and water information. 
image

After clicking Start. Post weight and supplemental water will be cleared. 
image

Previously, it only loaded the base weight. 
image

**Review by alexpiet — APPROVED** [review]
Thanks @XX-Yin! I'd move that picture from the comments to the main PR body so it gets added to the email

**Comment by hanhou** [comment]
Should we hold off on merging into `production_testing` until last week's changes are merged into `main` on Wednesday?

I don't know whether there is something like "scheduled protection" to a branch in github...

**Comment by alexpiet** [comment]
> Should we hold off on merging into `production_testing` until last week's changes are merged into `main` on Wednesday?
> 
> I don't know whether there is something like "scheduled protection" to a branch in github...

Yes @hanhou, I forgot. 
@XX-Yin can you undo the merge

**Comment by XX-Yin** [comment]
Thanks for reminder! I canceled the merge.

**Comment by alexpiet** [comment]
@XX-Yin You can merge this in now that the production merge is done

**Comment by XX-Yin** [comment]
Done!

**Pull request merged**
