### PR TITLE
Show video

### PR DESCRIPTION
**Pull request by XX-Yin**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:
Updated the bonsai layout file to automatically open the video visualization when bonsai is started. 

### What issues or discussions does this update address?
https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/351#event-12543503251

### Describe the expected change in behavior from the perspective of the experimenter
For behavior rigs, no. 
For ephys rigs, video visualization panels will be open automatically. 

### Describe any manual update steps for task computers
No 

### Was this update tested in 446/447?
Tested on my own computer.

### CODE REVIEW

**Comment by alexpiet** [comment]
@XX-Yin Can you test this in 447, specifically on a FIP rig (with FIP running)
@hagikent You should probably review this as well

**Comment by XX-Yin** [comment]
> @XX-Yin Can you test this in 447, specifically on a FIP rig (with FIP running) @hagikent You should probably review this as well

I have tested it on the behavior rig. The camera windows are open even the `--no-bonsai-ide` was set. @alexpiet do you know how to hide these windows?

**Comment by alexpiet** [comment]
> > @XX-Yin Can you test this in 447, specifically on a FIP rig (with FIP running) @hagikent You should probably review this as well
> 
> I have tested it on the behavior rig. The camera windows are open even the `--no-bonsai-ide` was set. @alexpiet do you know how to hide these windows?

- `--no-bonsai-ide` hides the bonsai IDE, not any visualizer windows opened by the workflow. 
- We might need to include a flag in `Settings_box#.csv` with whether we want the cameras to open.

**Comment by XX-Yin** [comment]
> > > @XX-Yin Can you test this in 447, specifically on a FIP rig (with FIP running) @hagikent You should probably review this as well
> > 
> > 
> > I have tested it on the behavior rig. The camera windows are open even the `--no-bonsai-ide` was set. @alexpiet do you know how to hide these windows?
> 
> * `--no-bonsai-ide` hides the bonsai IDE, not any visualizer windows opened by the workflow.
> * We might need to include a flag in `Settings_box#.csv` with whether we want the cameras to open.

Do you know how to hide the visualizer? 

One solution is to use a different layout file, but this increases maintenance.
image

**Comment by hagikent** [comment]
If you use BoxD, BehaviorCameras and FIPvisualizer windows will be automatically popped up. (otherwise one cannot run experiments)
This is saved in the layout file. When you don't need them, you can simply close them.

**Comment by alexpiet** [comment]
> If you use BoxD, BehaviorCameras and FIPvisualizer windows will be automatically popped up. (otherwise one cannot run experiments) This is saved in the layout file. When you don't need them, you can simply close them.

This should only be true if you start the FIP workflow, right?

**Comment by XX-Yin** [comment]
> If you use BoxD, BehaviorCameras and FIPvisualizer windows will be automatically popped up. (otherwise one cannot run experiments) This is saved in the layout file. When you don't need them, you can simply close them.

`BehaviorCameras` and `FIPvisualizer` are in different bonsai workflow and layout files from the `foraging.bonsai` and `foraging.bonsai.layout`, right? I only changed the `foraging.bonsai.layout`.

**Comment by alexpiet** [comment]
> > If you use BoxD, BehaviorCameras and FIPvisualizer windows will be automatically popped up. (otherwise one cannot run experiments) This is saved in the layout file. When you don't need them, you can simply close them.
> 
> `BehaviorCameras` and `FIPvisualizer` are in different bonsai workflow and layout files from the `foraging.bonsai` and `foraging.bonsai.layout`, right? I only changed the `foraging.bonsai.layout`.

Yes, the FIP workflow is separate, and will launch the FIP visualizers and the behavior cameras.

**Comment by XX-Yin** [comment]
@alexpiet @hagikent I think it can be merged, and people who don't use high-speed cameras can just close these windows.

**Comment by alexpiet** [comment]
> @alexpiet @hagikent I think it can be merged, and people who don't use high-speed cameras can just close these windows.

I'm not sure I understand. Is the behavior of this PR to make the high speed camera windows always open up? This would be very annoying in 447. Can we just use the already existing setting in `Settings_box#.csv` (HighSpeedCamera) to toggle whether we open the camera windows?

**Comment by XX-Yin** [comment]
> > @alexpiet @hagikent I think it can be merged, and people who don't use high-speed cameras can just close these windows.
> 
> I'm not sure I understand. Is the behavior of this PR to make the high speed camera windows always open up? This would be very annoying in 447. Can we just use the already existing setting in `Settings_box#.csv` (HighSpeedCamera) to toggle whether we open the camera windows?

I don't know how to toggle the `foraging.bonsai.layout` file from the code in the `foraging.bonsai`. I am not sure if it's possible.
One solution is to use different `foraging.bonsai.layout` files, but it will increase of complexity of maintenance.

**Comment by XX-Yin** [comment]
> > @alexpiet @hagikent I think it can be merged, and people who don't use high-speed cameras can just close these windows.
> 
> I'm not sure I understand. Is the behavior of this PR to make the high speed camera windows always open up? This would be very annoying in 447. Can we just use the already existing setting in `Settings_box#.csv` (HighSpeedCamera) to toggle whether we open the camera windows?

Yes, the high-speed camera windows always open up.

**Comment by alexpiet** [comment]
@XX-Yin Bruno says there is no way to logically toggle which visualizers are open based on input settings. Therefore we need to just have the 447 RAs close the extra windows (or maintain two layout files). 
- Can you make sure this PR is up to date with any changes that happened over the last week?
- Can you also label the camera windows with the box name and the camera view ("Side" or "Bottom")

**Comment by XX-Yin** [comment]
Hi Alex, thanks for updating this. Sure, I can make some changes to this PR

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
