### PR TITLE
Updated stagewidget position movement code

### PR DESCRIPTION
**Pull request by jessy-liao**
### Pull Request instructions:
- Please follow the [update protocol](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki/Software-Update-Procedures)
- Answer the questions below in detail. Your responses will be emailed to experimenters. 
- If the experimenters must do anything new, provide detailed step by step instructions on the [wiki](https://github.com/AllenNeuralDynamics/aind-behavior-blog/wiki)
- If computer maintainers need to manually update anything, provide detailed step by step instructions
- Use markdown syntax in order for your comments to be rendered reliably in the email: "1." instead of "1)", use four spaces for indents.
- If you use the keyword "skip email" in the title, it will skip the email updates
- Merges from "develop" into "production_testing" should use the keyword "production merge" in the title for reliable indexing of updates
- Merges from "production_testing" into "main" should use the keyword "update main"
  
### Describe changes:

Updated dynamic foraging code that interacts with stage widget to initially setup position for experiments. 
The stagewidget can now move position simultaneously so the dynamic foraging code needs to be updated as well. 

### What issues or discussions does this update address?

http://mpe-redirects/MPETracking/ItemID=3851

### Describe the expected change in behavior from the perspective of the experimenter

Initializing the stage position should be faster as they should move in parallel

### Describe any manual update steps for task computers

Normal deploy process

### Was this update tested in 446/447?

No, referring to Micah for testing since she implemented the original initial position code.

### CODE REVIEW

**Review by micahwoodard — DISMISSED** [review]
Yep this looks good to me as long as it's been tested and works the same

**Comment by micahwoodard** [comment]
@jessy-liao do you still need me to test this? I thought when we chatted yesterday you had a chance to test in person

**Comment by jessy-liao** [comment]
I just merge the changes related to B_StagePosition. If you could take a quick look again and see if everything looks okay I will merge afterwards.

**Comment by micahwoodard** [comment]
Was using older version of stage widget. Fix actually works

**Review by micahwoodard — APPROVED** [review]

**Pull request merged**
